//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tubeshade.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tubeshade.Server.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllLibraries {
            get {
                return ResourceManager.GetString("AllLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create library.
        /// </summary>
        internal static string Button_CreateLibrary {
            get {
                return ResourceManager.GetString("Button_CreateLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Button_Ignore {
            get {
                return ResourceManager.GetString("Button_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string Button_Rescan {
            get {
                return ResourceManager.GetString("Button_Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Button_Scan {
            get {
                return ResourceManager.GetString("Button_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan all videos.
        /// </summary>
        internal static string Button_ScanAll {
            get {
                return ResourceManager.GetString("Button_ScanAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Sponsor Block segments.
        /// </summary>
        internal static string Button_ScanSponsorBlock {
            get {
                return ResourceManager.GetString("Button_ScanSponsorBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan subscriptions.
        /// </summary>
        internal static string Button_ScanSubscriptions {
            get {
                return ResourceManager.GetString("Button_ScanSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Button_Subscribe {
            get {
                return ResourceManager.GetString("Button_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string Button_Unsubscribe {
            get {
                return ResourceManager.GetString("Button_Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update preferences.
        /// </summary>
        internal static string Button_UpdatePreferences {
            get {
                return ResourceManager.GetString("Button_UpdatePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string Filters_Availability {
            get {
                return ResourceManager.GetString("Filters_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any availability.
        /// </summary>
        internal static string Filters_Availability_Any {
            get {
                return ResourceManager.GetString("Filters_Availability_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Filters_Availability_not_available {
            get {
                return ResourceManager.GetString("Filters_Availability_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Filters_Availability_private {
            get {
                return ResourceManager.GetString("Filters_Availability_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Filters_Availability_public {
            get {
                return ResourceManager.GetString("Filters_Availability_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Filters_Channel {
            get {
                return ResourceManager.GetString("Filters_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All channels.
        /// </summary>
        internal static string Filters_Channels_All {
            get {
                return ResourceManager.GetString("Filters_Channels_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With files.
        /// </summary>
        internal static string Filters_Files {
            get {
                return ResourceManager.GetString("Filters_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_Files_All {
            get {
                return ResourceManager.GetString("Filters_Files_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With files.
        /// </summary>
        internal static string Filters_Files_With {
            get {
                return ResourceManager.GetString("Filters_Files_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without files.
        /// </summary>
        internal static string Filters_Files_Without {
            get {
                return ResourceManager.GetString("Filters_Files_Without", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string Filters_PageSize {
            get {
                return ResourceManager.GetString("Filters_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Filters_Search {
            get {
                return ResourceManager.GetString("Filters_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction.
        /// </summary>
        internal static string Filters_SortDirection {
            get {
                return ResourceManager.GetString("Filters_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Filters_SortDirection_ASC {
            get {
                return ResourceManager.GetString("Filters_SortDirection_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Filters_SortDirection_DESC {
            get {
                return ResourceManager.GetString("Filters_SortDirection_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Filters_SortVideoBy {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Filters_SortVideoBy_created_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Filters_SortVideoBy_modified_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_modified_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Filters_SortVideoBy_published_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_published_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Filters_SortVideoBy_random {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed.
        /// </summary>
        internal static string Filters_SortVideoBy_refreshed_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_refreshed_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video type.
        /// </summary>
        internal static string Filters_VideoType {
            get {
                return ResourceManager.GetString("Filters_VideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_VideoType_All {
            get {
                return ResourceManager.GetString("Filters_VideoType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestreams.
        /// </summary>
        internal static string Filters_VideoType_livestream {
            get {
                return ResourceManager.GetString("Filters_VideoType_livestream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts.
        /// </summary>
        internal static string Filters_VideoType_short {
            get {
                return ResourceManager.GetString("Filters_VideoType_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Filters_VideoType_video {
            get {
                return ResourceManager.GetString("Filters_VideoType_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string Filters_Viewed {
            get {
                return ResourceManager.GetString("Filters_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_Viewed_All {
            get {
                return ResourceManager.GetString("Filters_Viewed_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not viewed.
        /// </summary>
        internal static string Filters_Viewed_NotViewed {
            get {
                return ResourceManager.GetString("Filters_Viewed_NotViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string Filters_Viewed_Viewed {
            get {
                return ResourceManager.GetString("Filters_Viewed_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage path.
        /// </summary>
        internal static string Libraries_StoragePath {
            get {
                return ResourceManager.GetString("Libraries_StoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription schedule.
        /// </summary>
        internal static string Libraries_SubscriptionSchedule {
            get {
                return ResourceManager.GetString("Libraries_SubscriptionSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription schedule time zone.
        /// </summary>
        internal static string Libraries_SubscriptionTimeZone {
            get {
                return ResourceManager.GetString("Libraries_SubscriptionTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original no longer available.
        /// </summary>
        internal static string Original_NotAvailable {
            get {
                return ResourceManager.GetString("Original_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Pagination_First {
            get {
                return ResourceManager.GetString("Pagination_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Pagination_Last {
            get {
                return ResourceManager.GetString("Pagination_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} - {1} from {2}.
        /// </summary>
        internal static string Pagination_PageSummary {
            get {
                return ResourceManager.GetString("Pagination_PageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download automatically.
        /// </summary>
        internal static string Preferences_DownloadAutomatically {
            get {
                return ResourceManager.GetString("Preferences_DownloadAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download formats.
        /// </summary>
        internal static string Preferences_DownloadFormats {
            get {
                return ResourceManager.GetString("Preferences_DownloadFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestream count.
        /// </summary>
        internal static string Preferences_LivestreamCount {
            get {
                return ResourceManager.GetString("Preferences_LivestreamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback speed.
        /// </summary>
        internal static string Preferences_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Preferences_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player client.
        /// </summary>
        internal static string Preferences_PlayerClient {
            get {
                return ResourceManager.GetString("Preferences_PlayerClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short count.
        /// </summary>
        internal static string Preferences_ShortCount {
            get {
                return ResourceManager.GetString("Preferences_ShortCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video count.
        /// </summary>
        internal static string Preferences_VideoCount {
            get {
                return ResourceManager.GetString("Preferences_VideoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video or channel URL.
        /// </summary>
        internal static string Scan_Url_Placeholder {
            get {
                return ResourceManager.GetString("Scan_Url_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        internal static string Subscribed {
            get {
                return ResourceManager.GetString("Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Tasks_Action {
            get {
                return ResourceManager.GetString("Tasks_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string Tasks_Queued {
            get {
                return ResourceManager.GetString("Tasks_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh automatically.
        /// </summary>
        internal static string Tasks_RefreshAutomatically {
            get {
                return ResourceManager.GetString("Tasks_RefreshAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Tasks_Status_cancelled {
            get {
                return ResourceManager.GetString("Tasks_Status_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Tasks_Status_completed {
            get {
                return ResourceManager.GetString("Tasks_Status_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Tasks_Status_failed {
            get {
                return ResourceManager.GetString("Tasks_Status_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string Tasks_Status_in_progress {
            get {
                return ResourceManager.GetString("Tasks_Status_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Tasks_Status_queued {
            get {
                return ResourceManager.GetString("Tasks_Status_queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Tasks_Task {
            get {
                return ResourceManager.GetString("Tasks_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download video.
        /// </summary>
        internal static string Tasks_Type_download_video {
            get {
                return ResourceManager.GetString("Tasks_Type_download_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Tasks_Type_index {
            get {
                return ResourceManager.GetString("Tasks_Type_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh subscriptions.
        /// </summary>
        internal static string Tasks_Type_refresh_subscriptions {
            get {
                return ResourceManager.GetString("Tasks_Type_refresh_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex videos.
        /// </summary>
        internal static string Tasks_Type_reindex_videos {
            get {
                return ResourceManager.GetString("Tasks_Type_reindex_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan channel.
        /// </summary>
        internal static string Tasks_Type_scan_channel {
            get {
                return ResourceManager.GetString("Tasks_Type_scan_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Sponsor Block segments.
        /// </summary>
        internal static string Tasks_Type_scan_sponsor_block_segments {
            get {
                return ResourceManager.GetString("Tasks_Type_scan_sponsor_block_segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan subscriptions.
        /// </summary>
        internal static string Tasks_Type_scan_subscriptions {
            get {
                return ResourceManager.GetString("Tasks_Type_scan_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string Video_Chapter {
            get {
                return ResourceManager.GetString("Video_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Video_ExternalAvailability_not_available {
            get {
                return ResourceManager.GetString("Video_ExternalAvailability_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Video_ExternalAvailability_private {
            get {
                return ResourceManager.GetString("Video_ExternalAvailability_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Video_ExternalAvailability_public {
            get {
                return ResourceManager.GetString("Video_ExternalAvailability_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} likes.
        /// </summary>
        internal static string Video_Likes {
            get {
                return ResourceManager.GetString("Video_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Video_Resolution {
            get {
                return ResourceManager.GetString("Video_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Video_Speed {
            get {
                return ResourceManager.GetString("Video_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} views.
        /// </summary>
        internal static string Video_Views {
            get {
                return ResourceManager.GetString("Video_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
