//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tubeshade.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tubeshade.Server.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllLibraries {
            get {
                return ResourceManager.GetString("AllLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Button_Download {
            get {
                return ResourceManager.GetString("Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Button_Ignore {
            get {
                return ResourceManager.GetString("Button_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string Button_Rescan {
            get {
                return ResourceManager.GetString("Button_Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string Filters_Availability {
            get {
                return ResourceManager.GetString("Filters_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any availability.
        /// </summary>
        internal static string Filters_Availability_Any {
            get {
                return ResourceManager.GetString("Filters_Availability_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string Filters_Availability_not_available {
            get {
                return ResourceManager.GetString("Filters_Availability_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Filters_Availability_private {
            get {
                return ResourceManager.GetString("Filters_Availability_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Filters_Availability_public {
            get {
                return ResourceManager.GetString("Filters_Availability_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string Filters_Channel {
            get {
                return ResourceManager.GetString("Filters_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All channels.
        /// </summary>
        internal static string Filters_Channels_All {
            get {
                return ResourceManager.GetString("Filters_Channels_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With files.
        /// </summary>
        internal static string Filters_Files {
            get {
                return ResourceManager.GetString("Filters_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_Files_All {
            get {
                return ResourceManager.GetString("Filters_Files_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With files.
        /// </summary>
        internal static string Filters_Files_With {
            get {
                return ResourceManager.GetString("Filters_Files_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without files.
        /// </summary>
        internal static string Filters_Files_Without {
            get {
                return ResourceManager.GetString("Filters_Files_Without", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string Filters_PageSize {
            get {
                return ResourceManager.GetString("Filters_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Filters_Search {
            get {
                return ResourceManager.GetString("Filters_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort direction.
        /// </summary>
        internal static string Filters_SortDirection {
            get {
                return ResourceManager.GetString("Filters_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Filters_SortDirection_ASC {
            get {
                return ResourceManager.GetString("Filters_SortDirection_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Filters_SortDirection_DESC {
            get {
                return ResourceManager.GetString("Filters_SortDirection_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Filters_SortVideoBy {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Filters_SortVideoBy_created_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string Filters_SortVideoBy_modified_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_modified_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Filters_SortVideoBy_published_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_published_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Filters_SortVideoBy_random {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed.
        /// </summary>
        internal static string Filters_SortVideoBy_refreshed_at {
            get {
                return ResourceManager.GetString("Filters_SortVideoBy_refreshed_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video type.
        /// </summary>
        internal static string Filters_VideoType {
            get {
                return ResourceManager.GetString("Filters_VideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_VideoType_All {
            get {
                return ResourceManager.GetString("Filters_VideoType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestreams.
        /// </summary>
        internal static string Filters_VideoType_livestream {
            get {
                return ResourceManager.GetString("Filters_VideoType_livestream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts.
        /// </summary>
        internal static string Filters_VideoType_short {
            get {
                return ResourceManager.GetString("Filters_VideoType_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Filters_VideoType_video {
            get {
                return ResourceManager.GetString("Filters_VideoType_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string Filters_Viewed {
            get {
                return ResourceManager.GetString("Filters_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Filters_Viewed_All {
            get {
                return ResourceManager.GetString("Filters_Viewed_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not viewed.
        /// </summary>
        internal static string Filters_Viewed_NotViewed {
            get {
                return ResourceManager.GetString("Filters_Viewed_NotViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string Filters_Viewed_Viewed {
            get {
                return ResourceManager.GetString("Filters_Viewed_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string Pagination_First {
            get {
                return ResourceManager.GetString("Pagination_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Pagination_Last {
            get {
                return ResourceManager.GetString("Pagination_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} - {1} from {2}.
        /// </summary>
        internal static string Pagination_PageSummary {
            get {
                return ResourceManager.GetString("Pagination_PageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        internal static string Video_Chapter {
            get {
                return ResourceManager.GetString("Video_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} likes.
        /// </summary>
        internal static string Video_Likes {
            get {
                return ResourceManager.GetString("Video_Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Video_Speed {
            get {
                return ResourceManager.GetString("Video_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} views.
        /// </summary>
        internal static string Video_Views {
            get {
                return ResourceManager.GetString("Video_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
